--- 
abstract: Catalyst model to access mozilla using by MozRepl
author: Toru Yamaguchi <zigorou@cpan.org>
build_requires: 
  Test::WWW::Mechanize::Catalyst: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Model-MozRepl
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Exception: 0
  Catalyst::Model: 0
  MozRepl: 0.06
  Next: 0
version: 0.01
